spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dashboard
    username: root
    password: chlqus310@
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
jwt:
  grant-type: Bearer
  header: Authorization
  access-token:  60000000
  refresh-token: 259200000
  secret : secret-dashboard-19960928-by-youngjun